### ISSUE TITLE
[2.7.0] Trends data missing when using `fillMissingData()`

### ISSUE THREAD

**Issue by drbyte** [eliseekn/laravel-metrics#10]
Are there plans to add automated tests to this package?
These breaking changes (removed methods, and broken new methods) are frustrating when used with an application in production.

```php
$submissionTrends = LaravelMetrics::query(Submission::query()->where('submitted', 1))
    ->countBetween([$from, $to])
//    ->fillEmptyDates()
    ->fillMissingData()
    ->trends();
```

Using a simplified demo data set with two records between the following date range:
```php
// $from = "2023-10-15"
// $to = "2023-10-28
```

With `2.6.2` and `fillEmptyDates()` it correctly returned:
```
array:2 [▼ // app/Filament/Admin/Widgets/StatsOverview.php:48
  "labels" => array:14 [▼
    0 => "2023-10-15"
    1 => "2023-10-16"
    2 => "2023-10-17"
    3 => "2023-10-18"
    4 => "2023-10-19"
    5 => "2023-10-20"
    6 => "2023-10-21"
    7 => "2023-10-22"
    8 => "2023-10-23"
    9 => "2023-10-24"
    10 => "2023-10-25"
    11 => "2023-10-26"
    12 => "2023-10-27"
    13 => "2023-10-28"
  ]
  "data" => array:14 [▼
    0 => 0
    1 => 0
    2 => 1
    3 => 0
    4 => 0
    5 => 0
    6 => 0
    7 => 0
    8 => 0
    9 => 1
    10 => 0
    11 => 0
    12 => 0
    13 => 0
  ]
]
```

But with `2.7.0` and `fillMissingData()` it incorrectly gives data for only the first date in the range:
```
array:2 [▼ // app/Filament/Admin/Widgets/StatsOverview.php:48
  "labels" => array:1 [▼
    0 => "2023-10-15"
  ]
  "data" => array:1 [▼
    0 => 0
  ]
]
```

Removing `fillMissingData()` gives the correct non-zero values, but I do want to get the zero data for missing dates:
```
array:2 [▼ // app/Filament/Admin/Widgets/StatsOverview.php:48
  "labels" => array:2 [▼
    0 => "2023-10-17"
    1 => "2023-10-24"
  ]
  "data" => array:2 [▼
    0 => 1
    1 => 1
  ]
]
```

**Comment by eliseekn** [comment]
I see. I forget to specify in the documentation that the default between group is by years. Do you think it will be more easy to set by days by default ?

To solve your actual issue you must add groupByDay method:
```php
$submissionTrends = LaravelMetrics::query(Submission::query()->where('submitted', 1))
    ->countBetween([$from, $to])
    ->fillMissingData()
    ->groupByDay()
    ->trends();
```

For the tests I currently test manually using the demo version [https://github.com/eliseekn/laravel-metrics-demo](url)

**Comment by drbyte** [comment]
> Do you think it will be more easy to set by days by default ?

Since the raw data is based on days (ie: created_date), yes days is probably a smart default. 
That way, anyone seeing their data come back as days when they wanted months or years would easily see what likely needs changing.
But grouping by year (but still labeling it as a day) doesn't give any clues as to where to start changing things to get the right data.

Plus, in my case, my date range was only for days within a single month. So the sudden change to defaulting to grouping by year was very unexpected.

I can see where looking at historical trends might want to see things by-year to compare with prior years, so I see where your idea comes from, but I think it's more intuitive to start with days by default.

Admittedly my current use-case has me biased towards days. But v2.6.2 defaulted to days, so 2.7.0 should retain days IMO.

**Comment by eliseekn** [comment]
OK done, new release created. Thank you for your contribution.
