### ISSUE TITLE
Customize date field

### ISSUE THREAD

**Issue by zesinho** [eliseekn/laravel-metrics#11]
The created date lookup field is defined as `created_at`.
It would be handy to be able to overwrite the name of the lookup field, if it is named differently in an existing model.

**Comment by eliseekn** [comment]
Just use the `dateColumn` method to customize the date column as follows:

```php
Post::metrics()
    ->countByDay()
    ->dateColumn('published_at')
    ->trends();
```

Read the documentation to learn more about features.
