### ISSUE TITLE
Increment/Decrement percentage stat

### ISSUE THREAD

**Issue by yashiroiori** [eliseekn/laravel-metrics#12]
Hi, good work

It's possible to get de incremente/decrement porcentage for example of week/month/year sales??

Example:
January 2024 total: 500 decrement: 5% (respect December 2023)
February 2024 total: 500 increment: 2% (respect January 2024)

**Comment by eliseekn** [comment]
Hello! Thank you for using my package. Not sure, but I will think about adding a feature like this.

**Comment by eliseekn** [comment]
Hello, can you check this [v2.9.0-beta-1](https://github.com/eliseekn/laravel-metrics/releases/tag/v2.9.0-beta-1) for the feature you requested.

**Comment by eliseekn** [comment]
Hi, check [this beta release](https://github.com/eliseekn/laravel-metrics/releases/tag/v2.9.0-beta-2).

**Comment by yashiroiori** [comment]
> Hi, check [this beta release](https://github.com/eliseekn/laravel-metrics/releases/tag/v2.9.0-beta-2).

Excellent, let me test in my app
