### ISSUE TITLE
Format for date range

### ISSUE THREAD

**Issue by michele-widesrl** [eliseekn/laravel-metrics#4]
hi, I'm using your wonderful package to display the data of the last week (2023-09-25 / 2023-10-03) using the between method, I would like to format the labels with the classic Y-m-d format but the package forces me to use the toFormattedDateString. Is the possibility of choosing a custom format planned?

**Comment by eliseekn** [comment]
Hello! Thank you for using my package. I've made a new update based on your request. To enhance flexibility, I utilized the 'isoFormat' method from Carbon. As a result, I've introduced a new parameter called 'string $isoFormat = 'YYYY-MM-DD'' to the 'between' method.

If you want to achieve the 'Y-m-d' date format you desire, simply leave the parameter value as the default.

**Comment by michele-widesrl** [comment]
great job that's exactly what I was trying to do.
