### ISSUE TITLE
Filling days without results

### ISSUE THREAD

**Issue by ades4827** [eliseekn/laravel-metrics#5]
Hi, using periods like ->between I realized that the data returned by the query forms holes in the case of missing results.

For example using

->between( Carbon::now()->subDays(10)->format('Y-m-d'), Carbon::now()->format('Y-m-d'))

With the following dates:
2023-09-29 14:14:08
2023-10-01 14:14:03
2023-10-02 15:24:29
2023-10-02 15:24:35

I get 3 results.
If you want to use the trends in a graph it would be useful to have the possibility of obtaining the results for the other days too.

**Comment by eliseekn** [comment]
Hello! Thank you for using my package. I've implemented a new update based on your request. You can now utilize the 'fillEmptyDates' method to automatically fill empty dates with a default value when using the 'between' method. Check the README for an example.

**Comment by ades4827** [comment]
great job
