### ISSUE TITLE
[v2.6] Failed to parse time string (2023-10-2023-10-04): Double date specification

### ISSUE THREAD

**Issue by drbyte** [eliseekn/laravel-metrics#6]
Using the new `->fillEmptyDates()` triggers the following error (when used with `->byDay()` in my current dataset).

## Error:
> Could not parse '2023-10-2023-10-04': Failed to parse time string (2023-10-2023-10-04) at position 10 (2): Double date specification.
> `Eliseekn \ LaravelMetrics \ LaravelMetrics : line 482`

```php
// submissions_open and submissions_close are cast on the model to 'datetime'
$from = $activeShow->submissions_open->subDay()->format('Y-m-d');
$to = $activeShow->submissions_close->addDay()->format('Y-m-d');

// $from = "2023-09-22"
// $to = "2023-11-01

$submissionTrends = LaravelMetrics::query(Submission::query()->where('submitted', 1))
    ->count()
    ->between($from, $to)
    ->fillEmptyDates()
    ->byDay()
    ->trends();
```

<img width="1359" alt="Screen Shot 2023-10-04 at 7 13 05 PM" src="https://github.com/eliseekn/laravel-metrics/assets/404472/75bbfee1-b4b1-42ed-aeb6-160271bedb99">

**Comment by eliseekn** [comment]
Hello! Thank you for using my package. 

First of all you can not use 2 or more types of period in the same query, the last one will overwrite the others. So in your case ***byDay*** method will overwrite ***between*** method.

If you want to to get results by day  using the ***between*** method, just format the date. For example :

```php
$submissionTrends = LaravelMetrics::query(Submission::query()->where('submitted', 1))
    ->count()
    ->between($from, $to, 'DD MMM')
    ->fillEmptyDates()
    ->trends();
```

The method ***fillEmptyDates*** is not yet a global method and has been implemented to be used with ***between*** period. I will figure out if it can be used with others types of period.

**Comment by drbyte** [comment]
Thanks for your reply. 

I normally use `->between(from,to)->byWeek()` but was testing the `->fillEmptyDates()` since I saw it was the new addition to the readme.
In fact I only tested `->byDay()` because my `->byWeek()` results were coming back empty. So I was simply exploring the cause of that, and stumbled on the errors I reported above by using byDay().
