### ISSUE TITLE
How to use byDay(), byWeek() etc with between() ?

### ISSUE THREAD

**Issue by drbyte** [eliseekn/laravel-metrics#7]
Your comments in #6 now raise another question I have: 

What if I only want trends data BETWEEN CERTAIN DATES, and then wanted it shown by day/week? 

ie: I will NEVER want my entire model's data to be used for trend-reporting. I only care about a certain date range.  Anything before that would be related to a different event-period and I don't want your trends to be calculated on anything outside that range.

I want to know about records created during a date-range, then grouped by week, and then show the per-week values as trend data.

Right now it seems that you aggregate data from everything in the model ... which means if the model has data from multiple years, then "Week 3" will include all records created in "Week 3 from this year, plus last year, plus the year before". 

How, using your package, can we limit the selected records to a date range AND use the byDay and byWeek etc methods?

**Comment by eliseekn** [comment]
> Right now it seems that you aggregate data from everything in the model ... which means if the model has data from multiple years, then "Week 3" will include all records created in "Week 3 from this year, plus last year, plus the year before".

Not exactly. If not specified, byDay and byWeek methods refer to the current month and year, and byMonth to the current year. Model's data is aggregated from everything only using byYear method, but you are still able to specify a count that will generate a range. Same for byDay, byMonth and byWeek methods. Also the forDay, forMonth, forWeek and forYear methods will help you get more specific results.

> How, using your package, can we limit the selected records to a date range AND use the byDay and byWeek etc methods?

If I refer to the issue #6 you opened, it's not yet possible. Maybe adding methods like **groupByDay**, **groupByWeek** and **groupByMonth** when using the between method will solve this issue. I'll try to figure out.

**Comment by drbyte** [comment]
Thanks for the clarification. I understand better what your package is currently providing.

After discussing with my team we've decided to use the `between()` feature, and then slice the resulting collection by 7-day segments, and sum those results, and those per-week sums will be the data for our trends charts. This provides what our project currently needs.
It doesn't correctly identify actual "calendar weeks, starting on Sunday/Monday", but in our present scenario that's not critical ... but I can see how some projects would require that.

Thanks again for your package. It is super helpful.

**Comment by eliseekn** [comment]
Thank you too.
